export const consultas = [
  {
    id: 1,
    medico: 'Dr. João Silva',
    especialidade: 'Cardiologista',
    data: '27/04/1995',
    photo: 'https://github.com/alura-cursos.png',
    foiAgendado: true,
    foiAtendido: false,
  },
  {
    id: 2,
    medico: 'Dr. Maria',
    especialidade: 'Cardiologista',
    data: '27/04/1995',
    photo: 'https://github.com/alura-cursos.png',
    foiAgendado: false,
    foiAtendido: true,
  },
  {
    id: 3,
    medico: 'Dr. José',
    especialidade: 'Cardiologista',
    data: '27/04/1995',
    photo: 'https://github.com/alura-cursos.png',
    foiAgendado: true,
    foiAtendido: false,
  },
  {
    id: 4,
    medico: 'Dr. Ana',
    especialidade: 'Cardiologista',
    data: '27/04/1995',
    photo: 'https://github.com/alura-cursos.png',
    foiAgendado: false,
    foiAtendido: true,
  },
];
